Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2020-07, with the labels that each got.

#46 Add mattcary and saikat-royc as owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#50 Update Readme and go build
  Makefile
  README.md
  deploy/kubernetes/manifests/controller.yaml
  deploy/kubernetes/manifests/node.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#51 Update Makefile with image tags
  Dockerfile
  Makefile
  build/generate_image_tags.sh
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#52 Update readme for make instruction
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#53 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#55 Add resizer feature to Filestore driver
  README.md
  deploy/kubernetes/manifests/controller.yaml
  deploy/kubernetes/manifests/setup_cluster.yaml
  examples/kubernetes/demo-sc.yaml
  examples/kubernetes/sc-latebind.yaml
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/csi_driver/controller_unimpl.go
  pkg/csi_driver/gcfs_driver.go
  pkg/csi_driver/identity.go
  pkg/csi_driver/identity_test.go
  pkg/util/util.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L
