Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2021-03, with the labels that each got.

#107 add cloud-config and some more fixes
  cmd/main.go
  deploy/kubernetes/install_kustomize.sh
  go.mod
  go.sum
  pkg/cloud_provider/cloud.go
  pkg/cloud_provider/fake.go
  pkg/cloud_provider/file/file.go
  pkg/cloud_provider/token_source.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/csi_driver/gcfs_driver.go
  test/k8s-integration/main.go
  test/sanity/sanity_test.go
  vendor/gopkg.in/gcfg.v1/LICENSE
  vendor/gopkg.in/gcfg.v1/README
  vendor/gopkg.in/gcfg.v1/doc.go
  vendor/gopkg.in/gcfg.v1/errors.go
  vendor/gopkg.in/gcfg.v1/go1_0.go
  vendor/gopkg.in/gcfg.v1/go1_2.go
  vendor/gopkg.in/gcfg.v1/read.go
  vendor/gopkg.in/gcfg.v1/scanner/errors.go
  vendor/gopkg.in/gcfg.v1/scanner/scanner.go
  vendor/gopkg.in/gcfg.v1/set.go
  vendor/gopkg.in/gcfg.v1/token/position.go
  vendor/gopkg.in/gcfg.v1/token/serialize.go
  vendor/gopkg.in/gcfg.v1/token/token.go
  vendor/gopkg.in/gcfg.v1/types/bool.go
  vendor/gopkg.in/gcfg.v1/types/doc.go
  vendor/gopkg.in/gcfg.v1/types/enum.go
  vendor/gopkg.in/gcfg.v1/types/int.go
  vendor/gopkg.in/gcfg.v1/types/scan.go
  vendor/gopkg.in/warnings.v0/LICENSE
  vendor/gopkg.in/warnings.v0/README
  vendor/gopkg.in/warnings.v0/warnings.go
  vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XXL

#109 Update gcloud cluster list filter
  test/k8s-integration/cluster.go
Labels: approved, cncf-cla: yes, kind/failing-test, lgtm, release-note-none, size/S

#108 Release notes for release-0.4
  CHANGELOG/CHANGELOG-0.4.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note, size/M

#110 Clone master instead of pulling from archive
  test/k8s-integration/.dockerized-kube-version-defs
  test/k8s-integration/cluster.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/M

#111 driver binary reference fix in filestore image build + fsgroup policy overlay patch fix
  Dockerfile
  Makefile
  deploy/kubernetes/overlays/stable-master/fsgrouppolicy.yaml
  deploy/kubernetes/overlays/stable-master/kustomization.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#112 Fix driver image binary path in dockerfile COPY
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, size/S

#113 setup STAGINGVERSION when calling make driver from dockerfile
  Dockerfile
  Makefile
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/XS

#114 Changelog updates for release-0.4
  CHANGELOG/CHANGELOG-0.4.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/XS

#115 Cherrypick of #110, #111, #112, #113 from master to release-0.4
  CHANGELOG/CHANGELOG-0.4.md
  Dockerfile
  Makefile
  deploy/kubernetes/overlays/stable-master/fsgrouppolicy.yaml
  deploy/kubernetes/overlays/stable-master/kustomization.yaml
  test/k8s-integration/.dockerized-kube-version-defs
  test/k8s-integration/cluster.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#116 update rc overlay image to 0.4.0-rc2
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: approved, cncf-cla: yes, kind/documentation, release-note-none, size/S

#117 Update stable overlays to 0.4.0 driver image
  README.md
  deploy/kubernetes/images/stable-1-16/image.yaml
  deploy/kubernetes/images/stable-1-17/image.yaml
  deploy/kubernetes/images/stable-1-18/image.yaml
  deploy/kubernetes/images/stable-1-19/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#118 Cherry-pick #116, #117 to master to release-0.4
  README.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/images/stable-1-16/image.yaml
  deploy/kubernetes/images/stable-1-17/image.yaml
  deploy/kubernetes/images/stable-1-18/image.yaml
  deploy/kubernetes/images/stable-1-19/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, release-note-none, size/S

#119 Update prow rc images to use v0.4.0 driver image
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S
