Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2021-06, with the labels that each got.

#128 Fix roles needed to deploy the driver, and use v1 csidriver object for 1.20+ clusters
  deploy/kubernetes/overlays/stable-master/fsgrouppolicy.yaml
  deploy/project_setup.sh
Labels: approved, cncf-cla: yes, kind/cleanup, release-note, size/XS

#130 Switch to v1 Filestore backups
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
  test/e2e/tests/resize_e2e_test.go
  test/e2e/tests/setup_e2e_test.go
  test/remote/file.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/M

#125 Serialize volume operations for a given volume and return appropriate error codes
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/csi_driver/gcfs_driver.go
  pkg/csi_driver/node.go
  pkg/csi_driver/node_test.go
  pkg/util/volume_lock.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/XL

#132 Changelog for 0.5
  CHANGELOG/CHANGELOG-0.5.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note, size/M

#133 Update README for 0.5
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, release-note, size/XS

#135 Skip statd service on node startup if it's already running
  deploy/kubernetes/nfs_services_start.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, size/S

#136 Cherrypick #135 - Skip statd service on node startup if it's already running
  deploy/kubernetes/nfs_services_start.sh
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#137 update prow rc staging overlays to use 0.5.0-rc2
  CHANGELOG/CHANGELOG-0.5.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: approved, cncf-cla: yes, kind/feature, release-note, size/S

#139 Update stable driver images
  README.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/images/stable-1-16/image.yaml
  deploy/kubernetes/images/stable-1-17/image.yaml
  deploy/kubernetes/images/stable-1-18/image.yaml
  deploy/kubernetes/images/stable-1-18/stable/image.yaml
  deploy/kubernetes/images/stable-1-18/stable/kustomization.yaml
  deploy/kubernetes/images/stable-1-19/image.yaml
  deploy/kubernetes/images/stable-1-20/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, release-note, size/L

#140 Cherrypick #139 - Update stable driver images
  README.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/images/stable-1-16/image.yaml
  deploy/kubernetes/images/stable-1-17/image.yaml
  deploy/kubernetes/images/stable-1-18/image.yaml
  deploy/kubernetes/images/stable-1-18/stable/image.yaml
  deploy/kubernetes/images/stable-1-18/stable/kustomization.yaml
  deploy/kubernetes/images/stable-1-19/image.yaml
  deploy/kubernetes/images/stable-1-20/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: approved, cncf-cla: yes, kind/documentation, release-note, size/L

#131 poc for filestore csi driver installation
  test/k8s-integration/cluster.go
  test/k8s-integration/main.go
  test/run-k8s-integration.sh
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/google.golang.org/api/container/v1beta1/container_api.json
Labels: cncf-cla: yes, kind/feature, ok-to-test, release-note-none, size/XXL
