Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2022-12, with the labels that each got.

#392 update reviewers list
  OWNERS
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved, kind/documentation

#395 update reviewer list
  OWNERS
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved, kind/documentation

#397 Fix error categorization and handling
  pkg/csi_driver/controller.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_ops_manager.go
  pkg/csi_driver/node.go
  pkg/csi_driver/server.go
  pkg/csi_driver/utils.go
  pkg/metrics/metrics.go
  pkg/util/util.go
  pkg/webhook/webhook.go
Labels: kind/bug, lgtm, size/M, release-note-none, cncf-cla: yes, approved

#398 Simplify status.Error to status.Errorf to avoid fmt.Sprintf
  pkg/csi_driver/controller.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/node.go
  pkg/util/util.go
Labels: lgtm, size/M, release-note-none, cncf-cla: yes, approved, kind/cleanup, ok-to-test

#400 Update golang version
  Dockerfile
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved, kind/cleanup

#402 Fix firestore error logging and wrapping
  pkg/cloud_provider/cloud.go
  pkg/cloud_provider/fake.go
  pkg/cloud_provider/file/file.go
  pkg/cloud_provider/metadata/metadata.go
  pkg/csi_driver/controller.go
  test/k8s-integration/filter-junit.go
  test/k8s-integration/main.go
  test/remote/instance.go
Labels: kind/bug, lgtm, size/M, release-note-none, cncf-cla: yes, approved, ok-to-test
