Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2022-11, with the labels that each got.

#378 Update stable-master image to 1.3.5
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved, kind/documentation

#383 strict check for filestore service endpoints
  pkg/cloud_provider/file/file.go
  pkg/cloud_provider/file/file_test.go
  pkg/csi_driver/multishare_ops_manager.go
  test/k8s-integration/version.go
Labels: kind/bug, release-note, lgtm, size/L, cncf-cla: yes, approved

#384 Cherrypick #383 - strict check for filestore url
  pkg/cloud_provider/file/file.go
  pkg/cloud_provider/file/file_test.go
  pkg/csi_driver/multishare_ops_manager.go
  test/k8s-integration/version.go
Labels: kind/bug, release-note, lgtm, size/L, cncf-cla: yes, approved

#388 readme for 1.3.9
  README.md
Labels: release-note, cncf-cla: yes, approved, kind/documentation

#386 stable master overlay image update to 1.3.9
  CHANGELOG/CHANGELOG-1.3.md
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, size/XS, cncf-cla: yes, approved, kind/documentation, do-not-merge/hold

#381 Fix of driver error wrapping hides error codes
  cmd/main.go
  cmd/webhook/main.go
  go.mod
  go.sum
  pkg/cloud_provider/cloud.go
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/gcfs_driver.go
  pkg/csi_driver/multishare_ops_manager.go
  pkg/csi_driver/node.go
  pkg/csi_driver/server.go
  pkg/csi_driver/utils.go
  pkg/metrics/metrics.go
  test/e2e/tests/setup_e2e_test.go
  test/e2e/utils/utils.go
  test/k8s-integration/cluster.go
  test/k8s-integration/driver.go
  test/k8s-integration/filter-junit.go
  test/k8s-integration/main.go
  test/k8s-integration/utils.go
  test/k8s-integration/version.go
  test/remote/archiver.go
  test/remote/client-wrappers.go
  test/remote/file.go
  test/remote/instance.go
  test/remote/runner.go
  test/remote/setup-teardown.go
  test/remote/ssh.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README.md
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/google.golang.org/api/container/v1beta1/container-api.json
  vendor/google.golang.org/api/container/v1beta1/container-gen.go
  vendor/modules.txt
Labels: kind/bug, lgtm, release-note-none, size/XXL, cncf-cla: yes, approved, ok-to-test

#390 Silent volume provisioning surprise
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
Labels: kind/bug, release-note, lgtm, size/L, cncf-cla: yes, approved, ok-to-test
