Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2022-04, with the labels that each got.

#239 multishare metric emmision
  cmd/main.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/gcfs_driver.go
  pkg/csi_driver/multishare_controller.go
  pkg/metrics/metrics.go
Labels: kind/feature, lgtm, size/M, release-note-none, cncf-cla: yes, approved

#252 Handle uninitialized multishare controller object
  pkg/csi_driver/controller.go
Labels: kind/bug, release-note, lgtm, size/XS, cncf-cla: yes, approved

#249 fix error code mappings
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
Labels: release-note, lgtm, size/M, cncf-cla: yes, approved, kind/cleanup

#253 add share cloud provider implementation
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
Labels: release-note, size/M, cncf-cla: yes, approved, kind/cleanup

#254 Multishare create/delete volume based on APIs
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
  pkg/cloud_provider/file/file_test.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_controller_test.go
  pkg/csi_driver/multishare_ops_manager.go
  pkg/csi_driver/multishare_ops_manager_test.go
  pkg/csi_driver/volume_id.go
  pkg/util/cache.go
  pkg/util/cache_test.go
  pkg/util/multishare_defs.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: release-note, size/XXL, cncf-cla: yes, approved, kind/cleanup

#256 adding example for multishare storageclass and pvc
  examples/kubernetes/multishare/demo-pod.yaml
  examples/kubernetes/multishare/demo-sc.yaml
Labels: size/M, release-note-none, cncf-cla: yes, approved, kind/documentation

#257 dont consider multishare instances in error state as non-ready instances
  pkg/csi_driver/multishare_ops_manager.go
Labels: lgtm, release-note-none, size/XS, cncf-cla: yes, approved, kind/cleanup

#258 cap provisioner max retry interval per volume
  deploy/kubernetes/base/controller/controller.yaml
Labels: kind/feature, release-note, lgtm, size/XS, cncf-cla: yes, approved

#259 update logging for multishares volume provisioning
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
Labels: release-note-none, size/XS, cncf-cla: yes, approved, kind/cleanup

#260 Changelog 1.2
  CHANGELOG/CHANGELOG-1.2.md
Labels: release-note, lgtm, size/M, cncf-cla: yes, approved

#262 Implement cloud provider code for resize multishare instance
  pkg/cloud_provider/file/file.go
Labels: release-note, cncf-cla: yes, size/S, approved, kind/cleanup

#263 Implement cloudprovider code for resize multishare instance
  pkg/cloud_provider/file/file.go
Labels: release-note, cncf-cla: yes, size/S, approved, kind/cleanup

#261 use 1.2.0-rc2 for prow staging rc
  CHANGELOG/CHANGELOG-1.2.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note-none, size/XS, cncf-cla: yes, approved

#264 update readme and stable image for 1.2.0
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, size/M, cncf-cla: yes, approved
