Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2022-08, with the labels that each got.

#342 cherry pick #339 #341 to release-1.3
  Dockerfile
  pkg/csi_driver/controller.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_ops_manager.go
Labels: release-note, size/M, cncf-cla: yes, approved

#343 add 1.3.2 changelog and prow rc image
  CHANGELOG/CHANGELOG-1.3.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note, cncf-cla: yes, size/S, approved

#344 Cherrypick #343 to release-1.3
  CHANGELOG/CHANGELOG-1.3.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note-none, cncf-cla: yes, size/S, approved, kind/documentation

#345 update stable master image and readme 1.3.2
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, size/XS, cncf-cla: yes, approved, kind/documentation

#346 Cherrypick #345 to release-1.3
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note-none, size/XS, cncf-cla: yes, approved, kind/documentation

#337 Instance validation improvement when choosing eligible instances
  pkg/cloud_provider/file/fake.go
  pkg/csi_driver/multishare_controller_test.go
  pkg/csi_driver/multishare_ops_manager.go
  pkg/csi_driver/multishare_ops_manager_test.go
  pkg/csi_driver/utils.go
  test/remote/instance.go
Labels: release-note, lgtm, cncf-cla: yes, approved, size/XL, ok-to-test

#347 Add reserved ip range check and fail earlier if invalid
  pkg/csi_driver/controller.go
  pkg/csi_driver/multishare_ops_manager.go
  pkg/csi_driver/utils.go
Labels: release-note, lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#349 Typos fixed in windows_demo.md
  docs/kubernetes/windows_demo.md
Labels: release-note, lgtm, size/XS, needs-ok-to-test, cncf-cla: yes, approved, kind/documentation

#353 Typos `paramter` is fixed
  docs/kubernetes/backup.md
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved, kind/documentation, ok-to-test

#355 Fixed typos `PersitentVolume` & `RecalimPolicy`
  docs/kubernetes/cross-cluster.md
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#358 undo the hack of directly calling API
  test/k8s-integration/cluster.go
Labels: lgtm, size/L, release-note-none, cncf-cla: yes, approved

#357 add 1.3.3 changelog
  CHANGELOG/CHANGELOG-1.3.md
Labels: release-note, size/XS, needs-ok-to-test, cncf-cla: yes

#360 CHANGELOG for 1.3.3
  CHANGELOG/CHANGELOG-1.3.md
Labels: release-note, cncf-cla: yes, size/S, approved, kind/documentation

#361 Cherrypick #357, #360 to release-1.3
  CHANGELOG/CHANGELOG-1.3.md
Labels: size/M, release-note-none, cncf-cla: yes, approved, kind/documentation

#362 update prow rc master image to 1.3.3-rc1
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note, size/XS, cncf-cla: yes, approved, kind/documentation

#363 update stable master to 1.3.3
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, cncf-cla: yes, kind/documentation

#364 Cherrypick #363 - update stable master to 1.3.3
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note-none, size/XS, cncf-cla: yes, approved, kind/documentation

#351 Fixed typos in overlays.md
  docs/release/overlays.md
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved, kind/documentation, ok-to-test

#366 fix basePath set to empty
  pkg/cloud_provider/file/file.go
Labels: kind/bug, lgtm, release-note-none, size/XS, cncf-cla: yes, approved

#368 update prow rc image to 1.3.4
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note, size/XS, cncf-cla: yes, approved

#369 update readme change and stable-master overlay for 1.3.4
  CHANGELOG/CHANGELOG-1.3.md
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, cncf-cla: yes, size/S, approved, kind/documentation
