Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2022-06, with the labels that each got.

#290 verify test version is not master for gke managed driver test
  test/k8s-integration/main.go
  test/k8s-integration/utils.go
Labels: lgtm, release-note-none, size/XS, cncf-cla: yes, approved

#292 Fail instance eligibility check if any error encountered during checks
  pkg/csi_driver/multishare_ops_manager.go
Labels: kind/bug, release-note, lgtm, cncf-cla: yes, size/S, approved

#291 shared VPC ipAddress fix and ListShare region limit
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/multishare_ops_manager.go
Labels: kind/bug, lgtm, size/L, release-note-none, cncf-cla: yes, approved

#294 CHANGELOG for 1.2.3
  CHANGELOG/CHANGELOG-1.2.md
Labels: release-note, size/XS, cncf-cla: yes, approved, kind/documentation

#293 Cherrypick #291, #292 to release-1.2 branch
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/multishare_ops_manager.go
Labels: release-note, size/L, cncf-cla: yes, approved

#295 update prow rc image to 1.2.3
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: do-not-merge/release-note-label-needed, size/XS, cncf-cla: yes, approved

#296 update readme and stable master image to 1.2.3
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, size/XS, cncf-cla: yes, approved, kind/documentation

#298 Harden the invalid args checks for multi-share ops and add unit tests
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_controller_test.go
Labels: kind/bug, release-note, lgtm, size/L, cncf-cla: yes, approved

#301 fix typo in logging error of supported size
  pkg/csi_driver/multishare_controller.go
Labels: release-note, size/XS, cncf-cla: yes, approved

#302 CHANGELOG for 1.2.4
  CHANGELOG/CHANGELOG-1.2.md
Labels: release-note, size/XS, cncf-cla: yes, approved, kind/documentation

#304 1.2.4 image and readme
  README.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, size/XS, cncf-cla: yes, approved

#305 Cherrypick #304 Release 1.2.4
  README.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, size/XS, cncf-cla: yes, approved

#308 1.2.5 release note, image and readme
  CHANGELOG/CHANGELOG-1.2.md
  README.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: lgtm, size/L, release-note-none, cncf-cla: yes, approved

#309 Cherrypick #308 - Changelog, readme, image for release-1.2
  CHANGELOG/CHANGELOG-1.2.md
  README.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, size/L, cncf-cla: yes, approved

#310 add parallel option to run-k8s-integration.sh
  test/run-k8s-integration.sh
Labels: lgtm, release-note-none, size/XS, kind/failing-test, cncf-cla: yes, approved

#311 Check for instance READY state before placing a share on it.
  pkg/csi_driver/multishare_controller_test.go
  pkg/csi_driver/multishare_ops_manager.go
  pkg/csi_driver/multishare_ops_manager_test.go
Labels: do-not-merge/release-note-label-needed, size/L, cncf-cla: yes, approved, ok-to-test

#312 changelog for 1.2.6
  CHANGELOG/CHANGELOG-1.2.md
Labels: release-note, size/XS, cncf-cla: yes, approved, kind/documentation

#314 images and readme update for 1.2.6
  README.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: kind/feature, release-note, size/XS, cncf-cla: yes, approved

#315 images and readme update for 1.2.6
  README.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  deploy/kubernetes/images/stable-master/image.yaml
Labels: kind/feature, release-note, size/XS, cncf-cla: yes, approved

#316 update prow image to 1.2.7-rc1
  CHANGELOG/CHANGELOG-1.2.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note, size/XS, cncf-cla: yes, approved

#319 update stable image to 1.2.7
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: kind/feature, release-note, size/XS, cncf-cla: yes, approved

#320 Cherrypick #319 to release-1.2
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: kind/feature, release-note, size/XS, cncf-cla: yes, approved
