Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2023-06, with the labels that each got.

#528 Update debian base image to latest version for CVE fixes
  Dockerfile
Labels: lgtm, release-note-none, size/XS, cncf-cla: yes, approved, kind/cleanup

#527 Return InvalidArgument when can't create backup uri
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
Labels: kind/bug, release-note, lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#531 parallel backups scripts
  examples/kubernetes/backups/parallel/backup-volumesnapshotclass.yaml
  examples/kubernetes/backups/parallel/demo-sc.yaml
  examples/kubernetes/backups/parallel/demo-ss.yaml
  examples/kubernetes/backups/parallel/test-parallel-backups-same-vol.sh
  examples/kubernetes/backups/parallel/test-parallel-backups.sh
Labels: size/M, release-note-none, cncf-cla: yes, approved

#532 Fix bug where err is passed to CodeForError instead of createErr
  pkg/csi_driver/controller.go
Labels: lgtm, release-note-none, size/XS, cncf-cla: yes, approved

#535 Handle user error which is not wrapped as googleapi.Error
  pkg/cloud_provider/file/file.go
  pkg/cloud_provider/file/file_test.go
Labels: release-note, lgtm, size/M, cncf-cla: yes, approved

#536 issue where Finalizer is not added for pre-existing Filestore instances
  pkg/csi_driver/reconciler.go
Labels: kind/bug, release-note, lgtm, size/XS, cncf-cla: yes, approved

#540 CHANGELOG for 1.5.4
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, cncf-cla: yes, size/S, approved

#541 update prow rc with candidate 1.5.4-rc2
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note-none, size/XS, cncf-cla: yes, approved, kind/documentation

#537 move crd to v1, add parameter field
  pkg/apis/multishare/v1/doc.go
  pkg/apis/multishare/v1/register.go
  pkg/apis/multishare/v1/types.go
  pkg/apis/multishare/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/multishare/v1/doc.go
  pkg/client/clientset/versioned/typed/multishare/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/multishare/v1/fake/fake_instanceinfo.go
  pkg/client/clientset/versioned/typed/multishare/v1/fake/fake_multishare_client.go
  pkg/client/clientset/versioned/typed/multishare/v1/fake/fake_shareinfo.go
  pkg/client/clientset/versioned/typed/multishare/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/multishare/v1/instanceinfo.go
  pkg/client/clientset/versioned/typed/multishare/v1/multishare_client.go
  pkg/client/clientset/versioned/typed/multishare/v1/shareinfo.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/multishare/interface.go
  pkg/client/informers/externalversions/multishare/v1/instanceinfo.go
  pkg/client/informers/externalversions/multishare/v1/interface.go
  pkg/client/informers/externalversions/multishare/v1/shareinfo.go
  pkg/client/listers/multishare/v1/expansion_generated.go
  pkg/client/listers/multishare/v1/instanceinfo.go
  pkg/client/listers/multishare/v1/shareinfo.go
  pkg/csi_driver/gcfs_driver.go
  pkg/csi_driver/multishare_stateful_controller.go
  pkg/csi_driver/multishare_stateful_controller_test.go
  pkg/csi_driver/reconciler.go
  pkg/csi_driver/reconciler_test.go
  pkg/util/util.go
  stateful/crd/crd.yaml
  stateful/crd/example-instanceinfo.yaml
  stateful/crd/example-shareinfo.yaml
Labels: kind/feature, lgtm, release-note-none, cncf-cla: yes, approved, size/XL

#543 [release-1.3] Move to bullseye base image (Cherrypick #468, #528)
  Dockerfile
Labels: release-note, lgtm, cncf-cla: yes, size/S, approved, kind/cleanup

#544 soak 1.3.15-rc1 image with prow rc master overlay
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note-none, size/XS, cncf-cla: yes, approved, kind/documentation

#546 CHANGELOG-1.3 for 1.3.15
  CHANGELOG/CHANGELOG-1.3.md
Labels: release-note-none, size/XS, cncf-cla: yes, approved, kind/documentation

#548 update prow rc master to 1.4.6-rc1
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note-none, size/XS, cncf-cla: yes, approved

#549 Update go version to 1.20.5 for CVE fixes
  Dockerfile
  cmd/webhook/Dockerfile
Labels: kind/bug, release-note, size/XS, cncf-cla: yes, approved

#553 soak 1.3.16-rc1 in prow rc staging master
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note-none, cncf-cla: yes, approved

#554 update prow rc to 1.5.5-rc1
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note-none, size/XS, cncf-cla: yes, approved

#555 changelog for 1.3.16, 1.4.6, 1.5.5
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note-none, cncf-cla: yes, size/S, approved, kind/documentation

#556 80 share support for stateful driver
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_controller_test.go
  pkg/csi_driver/multishare_stateful_controller.go
  pkg/csi_driver/reconciler.go
Labels: kind/feature, lgtm, size/M, release-note-none, cncf-cla: yes, approved

#545 Link Filestore Quota Page in backup.md
  docs/kubernetes/backup.md
Labels: lgtm, release-note-none, size/XS, needs-ok-to-test, cncf-cla: yes, approved, kind/documentation

#560 Update changelog and prow tag
  CHANGELOG/CHANGELOG-1.5.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: lgtm, release-note-none, size/XS, cncf-cla: yes, approved
