Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2023-09, with the labels that each got.

#601 [release-1.3] Automated cherry pick of #535: Handle user error which is not wrapped as googleapi.Err
  pkg/cloud_provider/file/file.go
  pkg/cloud_provider/file/file_test.go
Labels: release-note, lgtm, size/M, cncf-cla: yes, approved

#602 [release-1.4] Automated cherry pick of #523: Use CodeForError when we call filestore API, as well as when
  pkg/cloud_provider/file/file.go
  pkg/cloud_provider/file/file_test.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_controller_test.go
  pkg/csi_driver/multishare_ops_manager.go
Labels: lgtm, size/L, release-note-none, cncf-cla: yes

#599 Bump go version to 1.20.8
  Dockerfile
Labels: release-note, size/XS, cncf-cla: yes
