Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2023-05, with the labels that each got.

#490 doc and images for filestorecsi images 1.5.0, 1.4.4, 1.3.13
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note-none, size/XS, cncf-cla: yes, approved, kind/documentation

#496 NFS lock release metrics
  cmd/main.go
  pkg/csi_driver/node.go
  pkg/csi_driver/node_test.go
  pkg/metrics/metrics.go
  pkg/releaselock/configmap_util.go
  pkg/releaselock/configmap_util_test.go
  pkg/releaselock/controller.go
  pkg/releaselock/controller_test.go
  pkg/releaselock/fake.go
  pkg/releaselock/rpc.go
Labels: release-note, lgtm, size/L, cncf-cla: yes, approved

#499 use namespaced Factory to enable namespaced role binding
  deploy/kubernetes/overlays/lockrelease/configmap_rbac.yaml
  pkg/csi_driver/gcfs_driver.go
Labels: lgtm, release-note-none, cncf-cla: yes, size/S, approved

#502 Update changelog and prow tag for 1.5.2-rc1
  CHANGELOG/CHANGELOG-1.5.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note, lgtm, cncf-cla: yes, size/S, approved

#503 Update README and stable-master image for 1.5.2
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved

#505 Update go version to 1.19.9
  Dockerfile
  cmd/webhook/Dockerfile
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved

#507 Update go version to 1.20.4
  Dockerfile
  cmd/webhook/Dockerfile
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved

#504 fixed issue where the webhook doesn't recognize -next as an invalid label
  pkg/webhook/storageclass.go
  pkg/webhook/storageclass_test.go
Labels: kind/bug, release-note, lgtm, cncf-cla: yes, size/S, approved

#517 Update prow tag to 1.5.3-rc1
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved

#518 Changelog for 1.5.3, 1.4.5, and 1.3.14
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
Labels: release-note, lgtm, size/M, cncf-cla: yes, approved

#519 sample yamls for max shares feature
  examples/kubernetes/multishare/maxshares/demo-sc-128.yaml
  examples/kubernetes/multishare/maxshares/demo-sc-256.yaml
  examples/kubernetes/multishare/maxshares/demo-sc-512.yaml
  examples/kubernetes/multishare/maxshares/demo-ss-128.yaml
  examples/kubernetes/multishare/maxshares/demo-ss-256.yaml
  examples/kubernetes/multishare/maxshares/demo-ss-512.yaml
Labels: size/L, release-note-none, cncf-cla: yes, approved

#520 Update README and stable-master image to v1.5.3
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved

#521 Replace PollOpErrorCode and IsUserError with CodeForError
  pkg/cloud_provider/file/file.go
  pkg/cloud_provider/file/file_test.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/multishare_controller.go
Labels: lgtm, size/L, release-note-none, cncf-cla: yes, approved

#524 Fix lock release logs
  pkg/csi_driver/node.go
  pkg/releaselock/configmap_util.go
Labels: kind/bug, release-note, lgtm, cncf-cla: yes, size/S, approved

#477 Set enterprise tier in backup documentation
  docs/kubernetes/backup.md
  examples/kubernetes/backups-restore/backup-volumesnapshotclass.yaml
  examples/kubernetes/backups-restore/backup.yaml
  examples/kubernetes/backups-restore/sc.yaml
  examples/kubernetes/backups/backup-different-region.yaml
  examples/kubernetes/backups/backup-same-region.yaml
  examples/kubernetes/backups/backup-volumesnapshotclass-diff-region.yaml
  examples/kubernetes/backups/backup-volumesnapshotclass-same-region.yaml
Labels: release-note, lgtm, cncf-cla: yes, size/S, approved, ok-to-test
