Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2023-03, with the labels that each got.

#445 Lock release controller
  cmd/main.go
  deploy/kubernetes/overlays/lockrelease/configmap_rbac.yaml
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/csi_driver/gcfs_driver.go
  pkg/csi_driver/gcfs_driver_test.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/node.go
  pkg/csi_driver/node_test.go
  pkg/csi_driver/node_unimpl.go
  pkg/releaselock/controller.go
  pkg/releaselock/controller_test.go
  pkg/util/configmap_util.go
  pkg/util/configmap_util_test.go
  test/sanity/sanity_test.go
  vendor/k8s.io/client-go/tools/leaderelection/OWNERS
  vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/metrics.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/multilock.go
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/client-go/util/retry/util.go
  vendor/modules.txt
Labels: release-note, lgtm, size/XXL, cncf-cla: yes, approved

#447 Fix backup source comparison logic for single share instances
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/util/util.go
Labels: kind/bug, release-note, lgtm, size/L, cncf-cla: yes, approved

#453 Bump cloudbuild and e2e test timeout
  cloudbuild.yaml
  test/run_e2e.sh
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved

#454 cherry pick #447 and #445 into release-1.4
  cloudbuild.yaml
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/util/util.go
  test/run_e2e.sh
Labels: release-note, lgtm, size/L, cncf-cla: yes, approved

#452 Update changelog-1.4 and prow tag
  CHANGELOG/CHANGELOG-1.4.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note, lgtm, cncf-cla: yes, size/S, approved

#455 Update stable-master image for v1.4.1
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved

#457 Fix pointer issue for lock release controller
  pkg/releaselock/controller.go
  pkg/releaselock/controller_test.go
Labels: kind/bug, release-note, lgtm, size/M, cncf-cla: yes, approved

#459 prow rc image to 1.4.2-rc1
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note-none, size/XS, cncf-cla: yes, approved, kind/documentation

#456 setup feature gate for configurable shares per instance
  cmd/main.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/csi_driver/gcfs_driver.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_ops_manager.go
  pkg/csi_driver/multishare_ops_manager_test.go
  pkg/csi_driver/node_test.go
  pkg/util/multishare_defs.go
Labels: kind/feature, release-note, lgtm, size/L, cncf-cla: yes, approved

#460 publish 1.4.2 image
  CHANGELOG/CHANGELOG-1.4.md
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: release-note, cncf-cla: yes, size/S, approved, kind/documentation
