Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2023-08, with the labels that each got.

#573 Automated cherry pick of #535: Handle user error which is not wrapped as googleapi.Err
  pkg/cloud_provider/file/file.go
  pkg/cloud_provider/file/file_test.go
Labels: lgtm, size/M, release-note-none, cncf-cla: yes, approved

#575 Update go version to 1.20.6 to fix CVE
  Dockerfile
  cmd/webhook/Dockerfile
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#581 Add tests for DeleteSnapshot
  pkg/csi_driver/controller_test.go
Labels: lgtm, size/M, release-note-none, needs-ok-to-test, cncf-cla: yes, approved, kind/cleanup

#580 Multishare Create Backup
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_controller_test.go
  pkg/csi_driver/volume_id.go
  pkg/util/multishare_defs.go
  pkg/util/util.go
Labels: kind/feature, release-note, lgtm, cncf-cla: yes, approved, size/XL, ok-to-test

#582 Add test for DeleteSnapshot Multishare
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
Labels: lgtm, size/M, release-note-none, cncf-cla: yes, approved, ok-to-test

#586 zonal large tier support
  pkg/csi_driver/controller.go
Labels: release-note, lgtm, cncf-cla: yes, size/S, approved

#585 Multishare restore
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_controller_test.go
  pkg/csi_driver/multishare_ops_manager.go
Labels: kind/feature, release-note, lgtm, cncf-cla: yes, approved, size/XL, ok-to-test

#590 Update Go version to 1.20.7 to fix CVEs
  Dockerfile
Labels: kind/bug, release-note, lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#594 [release-1.3]Update Go version to 1.20.7 to fix CVEs
  Dockerfile
  cmd/webhook/Dockerfile
Labels: kind/bug, release-note, lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#593 [release-1.5]Update Go version to 1.20.7 to fix CVEs
  Dockerfile
  cmd/webhook/Dockerfile
Labels: kind/bug, release-note, lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#592 [release-1.6]Update Go version to 1.20.7 to fix CVEs
  Dockerfile
  cmd/webhook/Dockerfile
Labels: kind/bug, release-note, lgtm, size/XS, cncf-cla: yes, approved, ok-to-test

#579 Updating changelog for release v1.6.1, v1.5.7, v1.4.7, v1.3.17
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.4.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
Labels: lgtm, size/M, release-note-none, cncf-cla: yes, approved, kind/documentation
