Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2023-12, with the labels that each got.

#737 Add NfsExportOptions parsing
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_controller_test.go
Labels: release-note, lgtm, cncf-cla: yes, approved, size/XL, ok-to-test

#741 [release-1.6] Update golang builder to 1.20.12
  Dockerfile
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved, kind/cleanup

#744 Add changelogs for latest patches
  CHANGELOG/CHANGELOG-1.3.md
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
Labels: lgtm, size/L, release-note-none, cncf-cla: yes, approved, kind/documentation

#745 [release-1.6] Update webhook go builder to 1.20.12
  cmd/webhook/Dockerfile
Labels: release-note, lgtm, size/XS, cncf-cla: yes, approved, kind/cleanup

#746 Fix issue where errors were reported as info
  pkg/csi_driver/controller.go
Labels: kind/bug, release-note, lgtm, size/M, cncf-cla: yes, approved, ok-to-test

#755 CVE-2023-48795: bump golang.org/x/crypto to v0.17.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: kind/bug, release-note, lgtm, size/XS, cncf-cla: yes, approved

#757 [release-1.5] Update go modules
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, size/M, release-note-none, cncf-cla: yes, approved

#765 Add changelogs for v1.5.15 and v1.6.10
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
Labels: lgtm, size/M, release-note-none, cncf-cla: yes, approved, kind/documentation

#767 Add changelog for v1.5.16, v1.6.11
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
Labels: lgtm, size/L, release-note-none, cncf-cla: yes, approved, kind/documentation

#766 Add generate-patch-release-notes.sh script
  hack/generate-patch-release-notes.sh
Labels: lgtm, size/M, release-note-none, cncf-cla: yes, approved
