Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2024-02, with the labels that each got.

#779 Automated cherry pick of #737: Add NfsExportOptions parsing#770: Refactor duplicate function#774: Disable NFSExportOptions by default
  cmd/main.go
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/csi_driver/gcfs_driver.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_controller_test.go
Labels: release-note, lgtm, cncf-cla: yes, approved, size/XL, ok-to-test

#787 Update supported tiers documentation
  README.md
Labels: lgtm, release-note-none, size/XS, cncf-cla: yes, approved, ok-to-test

#798 Change base image from bullseye to bookworm for CVE fixes
  Dockerfile
Labels: release-note, lgtm, cncf-cla: yes, size/S, approved, kind/cleanup

#802 Changelog for 1.6.13, 1.5.17, and update stable rc
  CHANGELOG/CHANGELOG-1.5.md
  CHANGELOG/CHANGELOG-1.6.md
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
  hack/generate-patch-release-notes.sh
Labels: lgtm, size/M, release-note-none, cncf-cla: yes, approved

#803 Update stable master to v1.6.13
  README.md
  deploy/kubernetes/images/stable-master/image.yaml
Labels: kind/feature, lgtm, size/M, release-note-none, cncf-cla: yes, approved
