Repository kubernetes-sigs/gcp-filestore-csi-driver, pull requests merged in 2024-01, with the labels that each got.

#754 Update documentation for deploying custom driver
  README.md
Labels: release-note, lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#769 Automated cherry pick of #746: Fix issue where errors were reported as info
  pkg/csi_driver/controller.go
Labels: release-note, lgtm, size/M, cncf-cla: yes, approved, ok-to-test

#770 Refactor duplicate function
  pkg/cloud_provider/file/fake.go
  pkg/cloud_provider/file/file.go
  pkg/csi_driver/controller.go
Labels: lgtm, size/L, release-note-none, cncf-cla: yes, approved, ok-to-test

#774 Disable NFSExportOptions by default
  cmd/main.go
  pkg/csi_driver/controller.go
  pkg/csi_driver/controller_test.go
  pkg/csi_driver/gcfs_driver.go
  pkg/csi_driver/multishare_controller.go
  pkg/csi_driver/multishare_controller_test.go
Labels: kind/feature, release-note, lgtm, size/L, cncf-cla: yes, approved, ok-to-test

#780 Bump prow rc candidate to 1.6.12
  deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Labels: release-note-none, size/XS, cncf-cla: yes, approved, kind/cleanup
